connect_compass_sass_variables_list:
    path: /sass-variables/{project}
    defaults: {_controller: MrConnectCompassBundle:SassVariable:list}


connect_compass_sass_variable_update:
    path: /sass-variables/{project}/update/{sassVariableName}
    defaults: {_controller: MrConnectCompassBundle:SassVariable:update, sassVariableName: null}


connect_compass_sass_variable_delete:
    path: /sass-variables/{project}/delete/{sassVariableName}
    defaults: {_controller: MrConnectCompassBundle:SassVariable:delete, sassVariableName: null}

connect_compass_sass_variable_add:
    path: /sass-variables/{project}/add
    defaults: {_controller: MrConnectCompassBundle:SassVariable:add}